name: Install gtnh2Packwiz
description: Installs gtnh2Packwiz via cmake
inputs:
  version:
    description: Version of gtnh2Packwiz to install
    required: false
    default: main
runs:
  using: composite
  steps:
    - name: Install boost
      uses: MarkusJx/install-boost@v2
      id: install-boost
      with:
        boost_version: 1.87.0
        platform_version: "20.04"
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: p1x3l101-10/gtnh-2-packwiz
        fetch-tags: true
    - name: Install runtime dependancies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: |
          libmagicenum
          nlohmann-json3
          libtomlplusplus
          liblog4cpp5v5
          libcurlpp0t64
    - name: Check version argument
      shell: bash
      id: version-check
      run: |
        if [[ ${{ inputs.version }} =~ '^v[0-9]+\.[0-9]+\.[0-9]+$' ]]; then
          echo "stable=true" >> $GITHUB_OUTPUT
        fi
    - name: Restore cached packwiz
      if: ${{ steps.version-check.stable == 'true' }}
      id: gtnh-2-packwiz-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/gtnh2Packwiz
        key: ${{ runner.os }}-gtnh-2-packwiz-${{ inputs.version }}
    - name: Install build dependancies
      if: ${{ ! steps.gtnh-2-packwiz-cache-restore.cache-hit }}
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        version: 1.0
        packages: |
          cmake
          pkgconf
          clang-20
          llvm-20
          llvm-20-dev
          ninja-build
          libmagicenum-dev
          nlohmann-json3-dev
          libtomlplusplus-dev
          liblog4cpp5-dev
          libcurlpp-dev
    - name: Checkout repo
      if: ${{ ! steps.gtnh-2-packwiz-cache-restore.cache-hit }}
      with:
        ref: ${{ inputs.version }}
        submodules: true
      uses: actions/checkout@v2
    - name: Build CMake Project
      if: ${{ ! steps.gtnh-2-packwiz-cache-restore.cache-hit }}
      uses: threeal/cmake-action@v2.1.0
      with: 
        generator: Ninja
        cxx-compiler: clang++
        options: |
          CMAKE_BUILD_TYPE=Release
          CMAKE_PREFIX_PATH=${{ steps.install-boost.outputs.BOOST_ROOT }}
          Boost_DIR=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib/cmake/Boost-1.87.0
          CMAKE_MODULE_PATH=${{ steps.install-boost.outputs.BOOST_ROOT }}/lib/cmake/Boost-1.87.0
          Boost_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}
    - name: Install to cache
      if: ${{ ! steps.gtnh-2-packwiz-cache-restore.cache-hit }}
      shell: bash
      run: |
        mkdir -p ~/gtnh2Packwiz
        cmake --install ./build --prefix ~/gtnh2Packwiz
    - name: Install cached build to /usr/local
      if: ${{ steps.gtnh-2-packwiz-cache-restore.cache-hit }}
      shell: bash
      run: sudo cp -r ~/gtnh2Packwiz/* /usr/local/
    - name: Cache installation
      if: ${{ steps.version-check.stable == 'true' }}
      uses: actions/cache@v4
      with:
        path: ~/gtnh2Packwiz
        key: ${{ runner.os }}-gtnh-2-packwiz-${{ inputs.version }}
        restore-keys: |
          ${{ runner.os }}-gtnh-2-packwiz-