name: Install Boost
description: Installs gtnh2Packwiz via cmake
inputs:
  version:
    description: Version to build
    required: true
  libraries:
    description: Space-separated list of libraries
    required: true
  toolset:
    description: Toolset to use
    required: false
    default: auto
  platform:
    description: Target platform
    required: false
    default: x64
  configuration:
    description: Configuration to build
    required: false
    default: Release
  static:
    description: Build static libraries
    required: false
    default: 0
  static-runtime:
    description: Link to the static runtime
    required: false
    default: 0
outputs:
  root:
    description: "Root path to boost installation"
    value: ${{ steps.boost.outputs.root }}
runs:
  using: composite
  steps:
    - name: Restore cached Boost
      id: boost-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/boost
        key: boost-${{ inputs.version }}-${{ hashFiles(inputs.libraries) }}
    - name: Install boost
      uses: mickem/build-boost@v1
      id: boost
      if: ${{ ! steps.boost-cache-restore.cache-hit }}
      with:
        version: ${{ inputs.version }}
        libraries: ${{ inputs.libraries }}
        platform: ${{ inputs.platform }}
        configuration: ${{ inputs.configuration }}
        static: ${{ inputs.static }}
        static-runtime: ${{ inputs.static-runtime }}
        directory: ~/boost
    - name: Cache Boost
      uses: actions/cache@v4
      if: ${{ ! steps.boost-cache-restore.cache-hit }}
      with:
        path: ~/boost
        key: boost-${{ inputs.version }}-${{ hashFiles(inputs.libraries) }}