# Validates that my program builds whenever there is a push to main
name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install gtnh-2-packwiz
      uses: ./.github/actions/install-program