# Creates a release on a new semver style git tag
name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        make_latest: true