# Runs valgrind to ensure that everything is safe
name: Valgrind leak checks
on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - Build
    branches: 
      - main
    types:
      - completed
jobs:
  build:
    name: Valgrind
    runs-on: ubuntu-latest
    steps:
    - name: Restore built binaries
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: /usr/local
        key: gtnh2Packwiz-usrLocal
    - name: Install runtime dependancies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: |
          libmagicenum
          nlohmann-json3
          libtomlplusplus
          liblog4cpp5v5
          libcurlpp0t64
    - name: Install test dependancies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: valgrind
        version: 1.0
    - name: Valgrind tests
      run: valgrind -v --leak-check=full --show-leak-kinds=all /usr/local/bin/gtnh-2-packwiz